//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecoMovie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public Film()
        {
            this.TopLists = new HashSet<TopList>();
        }
    
        public int ID_Filma { get; set; }
        public string Naziv_Filma { get; set; }
        public string Opis_Filma { get; set; }
        public Nullable<int> Likes { get; set; }
        public int ID_Zanra { get; set; }
        public string LemmaPlots { get; set; }
    
        public virtual Zanr Zanr { get; set; }
        public virtual ICollection<TopList> TopLists { get; set; }
    }
}
