//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecoMovie
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieDBEntities : DbContext
    {
        public MovieDBEntities()
            : base("name=MovieDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Film> Films { get; set; }
        public DbSet<Recnik> Recniks { get; set; }
        public DbSet<TopList> TopLists { get; set; }
        public DbSet<Zanr> Zanrs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
