//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecoMovie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recnik
    {
        public int ID_Recnik { get; set; }
        public string Recnik1 { get; set; }
        public int ID_Zanra { get; set; }
        public string RedukovanRecnik { get; set; }
    
        public virtual Zanr Zanr { get; set; }
    }
}
