//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecoMovie
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopList
    {
        public int ID_TopList { get; set; }
        public float Slicnost { get; set; }
        public int ID_Filma { get; set; }
        public string Film { get; set; }
    
        public virtual Film Film1 { get; set; }
    }
}
